import { useEffect, useState } from 'react';
import { AiOutlineArrowLeft } from 'react-icons/ai';

import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/router';

import { CardPoint } from '../../components/CardPoint';
import styles from '../../styles/pages/List.module.scss';
import { Data } from '../api/points';

const List: NextPage = () => {
  const router = useRouter();
  const [list, setList] = useState<Data[]>([]);

  useEffect(() => {
    const state = router.query.state as string;
    async function fetchData() {
      await fetch(`http://localhost:3000/api/point/${state}`)
        .then((response) => response.json())
        .then((data) => setList(data));
    }

    fetchData();
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Ecoleta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/icon.svg" />
      </Head>

      <nav className={styles.navbar}>
        <div className={styles.wrapperLinks}>
          <Link href="/">
            <a href="/">
              <Image
                src="/assets/logo.svg"
                alt="Ecoleta"
                width={150}
                height={50}
              />
            </a>
          </Link>

          <Link href="/">
            <a href="/" className={styles.link}>
              <AiOutlineArrowLeft color="#34CB79" size={24} />
              <span className={styles.textLink}>Voltar para home</span>
            </a>
          </Link>
        </div>
        <p>
          {list.length} pontos <span>encontrados</span>
        </p>
      </nav>

      <main className={styles.main}>
        <section className={styles.content}>
          {list.map((point) => (
            <CardPoint
              key={point.id}
              category={point.description}
              title={point.title}
              description={
                point.adress.city +
                ', ' +
                point.adress.state +
                ', ' +
                point.adress.street +
                ', N° ' +
                point.adress.number
              }
              imageURL={point.image}
            />
          ))}
        </section>
      </main>
    </div>
  );
};

export default List;
