import { useEffect, useState } from 'react';

import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';

import { CardPoint } from '../../components/CardPoint';
import { NavBar } from '../../components/NavBar';
import styles from '../../styles/pages/List.module.scss';
import { Entity } from '../api/points';

const List: NextPage = () => {
  const router = useRouter();
  const [collectionPoints, setCollectionPoints] = useState<Entity[]>([]);

  useEffect(() => {
    const state = router.query.state as string;
    async function fetchData() {
      await fetch(`http://localhost:3000/api/point/${state}`)
        .then((response) => response.json())
        .then((data) => setCollectionPoints(data));
    }

    fetchData();
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Ecoleta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/icon.svg" />
      </Head>

      <NavBar
        data={{
          icon: 'arrowLeft',
          description: 'Voltar para home',
          href: '/',
        }}
      />

      <main className={styles.main}>
        <section className={styles.wrapperQuantityPoints}>
          <div className={styles.quantityPoints}>
            <span>{collectionPoints.length} Pontos Encontrados</span>
          </div>
        </section>

        <section className={styles.content}>
          {collectionPoints.map((point) => (
            <CardPoint
              key={point.id}
              category={point.category}
              name={point.name}
              description={
                point.adress.city +
                ', ' +
                point.adress.state +
                ', ' +
                point.adress.street +
                ', N° ' +
                point.adress.number
              }
              imageURL={point.image}
            />
          ))}
        </section>
      </main>
    </div>
  );
};

export default List;
