/* eslint-disable react-hooks/exhaustive-deps */
import { useEffect, useState } from 'react';

import { collection, getDocs } from 'firebase/firestore';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';

import { CardPoint } from '../../components/CardPoint';
import { NavBar } from '../../components/NavBar';
import { db } from '../../services/firebase';
import styles from '../../styles/pages/List.module.scss';
import { Entity } from '../../types/entity';

import { data } from '..';

const List: NextPage = () => {
  const router = useRouter();
  const [collectionPoints, setCollectionPoints] = useState<Entity[]>([]);

  const dbInstance = collection(db, 'points');

  useEffect(() => {
    const state = router.query.state as string;

    // function getPointsByState() {
    //   getDocs(dbInstance)
    //     .then((data) => {
    //       setCollectionPoints(
    //         data.docs
    //           .map((item: any) => {
    //             return { ...item.data() };
    //           })
    //           .filter((point) => {
    //             return point.adress.state === state;
    //           })
    //       );
    //     })
    //     .catch((err) => {
    //       alert(err);
    //     });
    // }

    // getPointsByState();

    setCollectionPoints(
      data.filter((point) => {
        return point.adress.state === state;
      })
    );
  }, [router.query.state]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Ecoleta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/icon.svg" />
      </Head>

      <NavBar
        data={{
          icon: 'arrowLeft',
          description: 'Voltar para home',
          href: '/',
        }}
      />

      <main className={styles.main}>
        <section className={styles.wrapperQuantityPoints}>
          <div className={styles.quantityPoints}>
            <span>{collectionPoints.length} Pontos Encontrados</span>
          </div>
        </section>

        <section className={styles.content}>
          {collectionPoints.map((point) => (
            <CardPoint
              key={point.id}
              category={point.category}
              name={point.name}
              description={
                point.adress.city +
                ', ' +
                point.adress.state +
                ', ' +
                point.adress.street +
                ', N° ' +
                point.adress.number
              }
              imageURL={point.image}
            />
          ))}
        </section>
      </main>
    </div>
  );
};

export default List;
