import type { NextPage } from 'next';
import Head from 'next/head';

import { NavBar } from '../components/NavBar';
import styles from '../styles/pages/Login.module.scss';

const Login: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ecoleta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/icon.svg" />
      </Head>
      <NavBar
        data={{
          icon: 'exit',
          description: 'Voltar para home',
          href: '/',
        }}
      />

      <main className={styles.main}>
        <form className={styles.form}>
          <h1>Faça seu login</h1>
          <input type="text" placeholder="E-mail" />
          <input type="password" placeholder="Senha" />
          <button type="submit">Entrar</button>
        </form>
      </main>
    </div>
  );
};

export default Login;
