import { AiOutlineArrowLeft } from 'react-icons/ai';

import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import styles from '../styles/pages/Login.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ecoleta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/icon.svg" />
      </Head>
      <nav className={styles.navbar}>
        <div className={styles.wrapperLinks}>
          <Link href="/">
            <a href="/">
              <Image
                src="/assets/logo.svg"
                alt="Ecoleta"
                width={150}
                height={50}
              />
            </a>
          </Link>

          <Link href="/">
            <a href="/" className={styles.link}>
              <AiOutlineArrowLeft color="#34CB79" size={24} />
              <span className={styles.textLink}>Voltar para o início</span>
            </a>
          </Link>
        </div>
      </nav>

      <main className={styles.main}>
        <form className={styles.form}>
          <h1>Faça seu login</h1>
          <input type="text" placeholder="E-mail" />
          <input type="password" placeholder="Senha" />
          <button type="submit">Entrar</button>
        </form>
      </main>
    </div>
  );
};

export default Home;
