import type { NextPage } from 'next';
import Head from 'next/head';

import { FormRegister } from '../components/FormRegister';
import { NavBar } from '../components/NavBar';
import styles from '../styles/pages/Register.module.scss';

const Register: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ecoleta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/icon.svg" />
      </Head>

      <NavBar
        data={{
          icon: 'arrowLeft',
          description: 'Voltar para home',
          href: '/',
        }}
      />

      <main className={styles.main}>
        <FormRegister />
      </main>
    </div>
  );
};

export default Register;
