import { useState } from 'react';
import { AiOutlineArrowLeft } from 'react-icons/ai';

import { collection, addDoc } from 'firebase/firestore';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import styles from '../styles/pages/Register.module.scss';
import { app, database } from '../utils/firebase';

type Entitie = {
  name: string;
  adress: {
    street: string;
    city: string;
    state: string;
    number: number;
  };
  items?: {
    name: string;
  }[];
};

const Register: NextPage = () => {
  const [entities, setEntities] = useState<Entitie>({} as Entitie);
  const dbInstance = collection(database, 'entities');
  const handleSaveEntitie = async (e: any) => {
    e.preventDefault();
    try {
      await addDoc(dbInstance, {
        entities: entities,
      });
    } catch (error) {
      console.log(error);
    }

    console.log(entities);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Ecoleta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/icon.svg" />
      </Head>

      <nav className={styles.navbar}>
        <Link href="/">
          <a href="/">
            <Image
              src="/assets/logo.svg"
              alt="Ecoleta"
              width={150}
              height={50}
            />
          </a>
        </Link>

        <Link href="/">
          <a href="/" className={styles.link}>
            <AiOutlineArrowLeft color="#34CB79" size={24} />
            <span className={styles.textLink}>Voltar para home</span>
          </a>
        </Link>
      </nav>

      <main className={styles.main}>
        <form className={styles.form}>
          <h1 className={styles.title}>
            Cadastro do <br /> ponto de coleta
          </h1>
          <h3 className={styles.subTitle}>Dados da entidade</h3>
          <label htmlFor="name" className={styles.label}>
            Nome da entidade
          </label>
          <input
            type="text"
            id="name"
            className={styles.inputName}
            onChange={(e) => setEntities({ ...entities, name: e.target.value })}
          />
          <section className={styles.adressOne}>
            <section className={styles.wrapper}>
              <label htmlFor="adressName" className={styles.label}>
                Endereço
              </label>
              <input
                type="text"
                id="adressName"
                className={styles.inputAdressName}
                onChange={(e) =>
                  setEntities({
                    ...entities,
                    adress: { ...entities.adress, street: e.target.value },
                  })
                }
              />
            </section>
            <section className={styles.wrapper}>
              <label
                htmlFor="adressNumber"
                className={styles.label}
                style={{
                  marginLeft: '50%',
                }}
              >
                Número
              </label>
              <input
                type="text"
                id="adressNumber"
                className={styles.inputAdressNumber}
                onChange={(e) =>
                  setEntities({
                    ...entities,
                    adress: {
                      ...entities.adress,
                      number: Number(e.target.value),
                    },
                  })
                }
              />
            </section>
          </section>
          <section className={styles.adressTwo}>
            <section className={styles.wrapper}>
              <label htmlFor="adressCity" className={styles.label}>
                Cidade
              </label>
              <input
                type="text"
                id="adressCity"
                className={styles.inputAdressCity}
                onChange={(e) =>
                  setEntities({
                    ...entities,
                    adress: { ...entities.adress, city: e.target.value },
                  })
                }
              />
            </section>
            <section className={styles.wrapper}>
              <label
                htmlFor="adressState"
                className={styles.label}
                style={{
                  marginLeft: '5%',
                }}
              >
                Estado
              </label>
              <input
                type="text"
                id="adressState"
                className={styles.inputAdressState}
                onChange={(e) =>
                  setEntities({
                    ...entities,
                    adress: { ...entities.adress, state: e.target.value },
                  })
                }
              />
            </section>
          </section>
          <section className={styles.titleItens}>
            <h3>Ítens de coleta</h3>
            <span>Selecione um ou mais ítens abaixo</span>
          </section>

          <section className={styles.items}>
            <div className={styles.item}>
              <Image
                src="/assets/lamps.svg"
                alt="Lâmpadas"
                width={60}
                height={60}
              />
              <span className={styles.textSpan}>Lâmpadas</span>
            </div>
            <div className={styles.item}>
              <Image
                src="/assets/batteries.svg"
                alt="Pilhas e Baterias"
                width={60}
                height={60}
              />
              <span className={styles.textSpan}>Pilhas e Baterias</span>
            </div>
            <div className={styles.item}>
              <Image
                src="/assets/papers.svg"
                alt="Papéis e Papelão"
                width={60}
                height={60}
              />
              <span className={styles.textSpan}>Papéis e Papelão</span>
            </div>
            <div className={styles.item}>
              <Image
                src="/assets/electronics.svg"
                alt="Resíduos Eletrônicos"
                width={60}
                height={60}
              />
              <span className={styles.textSpan}>Resíduos Eletrônicos</span>
            </div>
            <div className={styles.item}>
              <Image
                src="/assets/organic.svg"
                alt="Resíduos Orgânicos"
                width={60}
                height={60}
              />
              <span className={styles.textSpan}>Resíduos Orgânicos</span>
            </div>
            <div className={styles.item}>
              <Image
                src="/assets/oil.svg"
                alt="Óleo de Cozinha"
                width={60}
                height={60}
              />
              <span className={styles.textSpan}>Óleo de Cozinha</span>
            </div>
          </section>
          <section className={styles.wrapperButton}>
            <button
              type="submit"
              className={styles.button}
              onClick={(e) => handleSaveEntitie(e)}
            >
              Cadastrar ponto de coleta
            </button>
          </section>
        </form>
      </main>
    </div>
  );
};

export default Register;
