import { useState } from 'react';

import type { NextPage } from 'next';
import Head from 'next/head';

import { NavBar } from '../components/NavBar';
import { useUser } from '../hooks/useUser';
import styles from '../styles/pages/Login.module.scss';

type IUser = {
  email: string;
  password: string;
};

const SignIn: NextPage = () => {
  const [user, setUser] = useState<IUser>({} as IUser);
  const { createUser } = useUser();
  function handleLogin(e: any) {
    e.preventDefault();

    createUser(user);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Ecoleta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/icon.svg" />
      </Head>
      <NavBar
        data={{
          icon: 'exit',
          description: 'Voltar para home',
          href: '/',
        }}
      />

      <main className={styles.main}>
        <form className={styles.form}>
          <h1>Faça seu cadastro</h1>
          <input
            type="text"
            placeholder="E-mail"
            onChange={(e) => setUser({ ...user, email: e.target.value })}
          />
          <input
            type="password"
            placeholder="Senha"
            onChange={(e) => setUser({ ...user, password: e.target.value })}
          />
          <button
            type="submit"
            onClick={(e) => {
              handleLogin(e);
            }}
          >
            Cadastrar
          </button>
        </form>
      </main>
    </div>
  );
};

export default SignIn;
